apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-merger-config
  labels:
    app: pdf-merger-api
data:
  APP_NAME: pdf-merger-api
  LOG_LEVEL: INFO
  ENVIRONMENT: production
  S3_ENDPOINT_URL: http://localstack:4566
  S3_BUCKET: pdf-merger
  S3_REGION: us-east-1
  MAX_UPLOAD_SIZE_MB: "25"
  MAX_MERGE_FILES: "20"
  OTEL_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector:4317
  OTEL_SERVICE_NAME: pdf-merger-api
