{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "pdf-merger.fullname" . }}
  labels:
    {{- include "pdf-merger.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "pdf-merger.fullname" . }}
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.prometheusServer | quote }}
        metricName: http_requests_total
        threshold: {{ .Values.keda.threshold | quote }}
        query: sum(rate(http_requests_total{job="pdf-merger-api"}[2m]))
{{- end }}
