apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdf-merger.fullname" . }}-secrets
  labels:
    {{- include "pdf-merger.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}
